version: "3"

networks:
  my_network: {}

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - my_network
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    container_name: spring-app-container
    ports:
      - 8443:8443
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - my_network
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.angular
    container_name: frontend-container
    ports:
      - 80:80
      - 443:443
    depends_on:
      - spring-app
    networks:
      - my_network
